theme: minimal
title: Smile
description: Aplikasi Smile untuk membantu mahasiswa dalam menyeimbangkan kembali mood serta mengurangi tingkat stress dengan fitur-fitur yang dapat membantu meredakan stress dan manajemen aktivitas serta mood mahasiswa.
