theme: minima
title: Smile
description: Aplikasi Smile adalah aplikasi manajemen mood untuk membantu mahasiswa dalam menyeimbangkan kembali mood serta mengurangi tingkat stress dengan fitur-fitur yang dapat membantu meredakan stress dan manajemen aktivitas serta mood mahasiswa.
